FROM python:3.11.4

WORKDIR /app

COPY business_service.py .
COPY requirements.txt .

RUN pip install -r requirements.txt

CMD ["uvicorn", "business_service:app", "--host", "0.0.0.0", "--port", "8000"]